# Лендинг glava.family (и запросы по IP — тоже лендинг)
server {
    listen 80 default_server;
    server_name glava.family www.glava.family _;
    root /var/www/glava.family;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}
